# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'pry'
gem "rspec"
gem 'http'
gem 'diffy'
gem 'paint'
gem 'tty-reader'
gem 'tty-pager'

gem "rake", "~> 12.3"
