require_relative 'lib/scenarios_list'
require_relative 'lib/scenario_runner'
require_relative 'lib/interactive_ui'
require_relative 'lib/logging_ui'

task :default do
  list = ScenariosList.new('./scenarios')

  ui = if ENV['CI']
         LoggingUI.new(STDOUT)
       else
         InteractiveUI.new(STDOUT)
       end

  list.all.each do |scenario|
    ScenarioRunner.new(scenario, ui: ui).call
  end

  ui.summary
end
