require 'pry'

task :default do
  require_relative 'lib/request_runner'

  Dir['./requests/*'].sort.each do |request_path|
    RequestRunner.new(request_path).call
  end
end

task :scenarios, [:path] do |t, args|
  require_relative 'lib/scenarios_list'
  # require_relative 'lib/scenario_runner'

  scenarios_list = ScenariosList.new(  './lib/fixtures/scenarios')
  puts args[:path].inspect
  exit 1

  scenarios = tree.scenarios_for_path(path)

  scenarios.each do |scenario|
    ScenarioRunner.new(scenario).call
  end
end
