# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - add-circleci-integration
    docker:
      - image: jumski/super-octo-mafia-circleci:latest
    working_directory: ~/repo
    steps:
      - checkout

      # Gemfile
      - restore_cache:
          keys:
          - v1-ruby-dependencies-{{ checksum "tests/api/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-ruby-dependencies-
      - run:
          name: install test dependencies
          command: |
            cd tests/api
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-ruby-dependencies-{{ checksum "tests/api/Gemfile.lock" }}

      # requirements.txt
      - restore_cache:
          keys:
          - v1-python-dependencies-{{ checksum "backend_python/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-python-dependencies-
      - run:
          name: install python dependencies
          command: |
            cd backend_python
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.pyenv/versions/3.6.4/
          key: v1-python-dependencies-{{ checksum "backend_python/requirements.txt" }}

      # server
      - run:
          name: start server in background
          background: true
          command: |
              cd backend_python
              ./run_server

      # tests
      - run:
          name: start server and run tests
          command: |
            sleep 3
            cd tests/api
            bundle exec rake

      # collect reports
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results
